<?php
/** One payslip as a printable page. @var array $slip @var array $lines */
$allow = array_values(array_filter($lines, static fn ($l) => $l['type'] === 'allowance'));
$deduct = array_values(array_filter($lines, static fn ($l) => $l['type'] === 'deduction'));
$earnings = array_merge([['label' => 'Basic salary', 'amount' => $slip['basic']]], $allow);
$rows = max(count($earnings), count($deduct));
$n = static fn ($v): string => number_format((float) $v, 2);
$status = $slip['run_status'] === 'paid' ? 'Paid' : ($slip['status'] === 'confirmed' ? 'Confirmed' : 'Draft');
?>
<article class="slip">
  <?php if ($status === 'Draft'): ?><p class="slip__draft">Draft, not yet confirmed</p><?php endif; ?>
  <header class="slip__head">
    <div>
      <img src="<?= e(url('logo-automate.svg')) ?>" alt="<?= e(company_name()) ?>" width="170" height="39">
      <p class="slip__addr"><?= e(company_name()) ?><br><?= implode('<br>', array_map('e', array_slice(office_lines(), 1))) ?></p>
    </div>
    <div class="slip__title">
      <h1>Payslip</h1>
      <p><?= e(period_label($slip['period'])) ?></p>
      <p class="slip__status"><?= e($status) ?><?= $slip['pay_date'] ? ' · Pay date ' . e(fmt_date($slip['pay_date'])) : '' ?></p>
    </div>
  </header>

  <section class="slip__who">
    <dl>
      <dt>Employee</dt><dd><?= e($slip['emp_name']) ?></dd>
      <dt>Employee code</dt><dd><?= e($slip['emp_code']) ?></dd>
      <dt>Designation</dt><dd><?= e((string) $slip['designation']) ?: '-' ?></dd>
      <dt>Department</dt><dd><?= e((string) $slip['department']) ?: '-' ?></dd>
    </dl>
    <dl>
      <dt>Date of joining</dt><dd><?= e(fmt_date($slip['join_date'])) ?></dd>
      <dt>CNIC</dt><dd><?= e((string) $slip['cnic']) ?: '-' ?></dd>
      <dt>Bank</dt><dd><?= e(trim((string) $slip['bank_name'])) ?: '-' ?></dd>
      <dt>Account / IBAN</dt><dd><?= e((string) $slip['bank_iban']) ?: '-' ?></dd>
    </dl>
  </section>

  <table class="slip__table">
    <thead><tr><th>Earnings</th><th class="num"><?= e($slip['currency']) ?></th><th>Deductions</th><th class="num"><?= e($slip['currency']) ?></th></tr></thead>
    <tbody>
    <?php for ($i = 0; $i < $rows; $i++): ?>
      <tr>
        <td><?= isset($earnings[$i]) ? e($earnings[$i]['label']) : '' ?></td><td class="num"><?= isset($earnings[$i]) ? e($n($earnings[$i]['amount'])) : '' ?></td>
        <td><?= isset($deduct[$i]) ? e($deduct[$i]['label']) : '' ?></td><td class="num"><?= isset($deduct[$i]) ? e($n($deduct[$i]['amount'])) : '' ?></td>
      </tr>
    <?php endfor; ?>
    </tbody>
    <tfoot>
      <tr><th>Gross pay</th><th class="num"><?= e($n($slip['gross'])) ?></th><th>Total deductions</th><th class="num"><?= e($n($slip['deductions'])) ?></th></tr>
    </tfoot>
  </table>

  <section class="slip__net">
    <div><p>Net pay</p><p class="slip__words"><?= e($slip['currency']) ?> <?= e(amount_in_words((float) $slip['net'])) ?> only</p></div>
    <strong><?= e($slip['currency']) ?> <?= e($n($slip['net'])) ?></strong>
  </section>
  <?php if ($slip['notes']): ?><p class="slip__note"><?= e($slip['notes']) ?></p><?php endif; ?>

  <footer class="slip__foot">
    <p>This payslip was generated by <?= e(company_name()) ?>'s HR system and does not need a signature.</p>
    <p>Questions about your pay? Contact HR<?= setting('hr_email', '') ? ' at ' . e(explode(',', (string) setting('hr_email', ''))[0]) : '' ?>.</p>
  </footer>
</article>
